# Generated by Django 5.0.1 on 2024-01-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_rename_decsription_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='docs.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
