# Generated by Django 5.0.3 on 2024-03-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
